# Generated by Django 2.2.3 on 2019-07-15 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.CharField(default='', max_length=300)),
                ('image_url', models.URLField(default=None, null=True)),
                ('isbn', models.CharField(default=None, max_length=13)),
                ('writer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='books.Author')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='works',
            field=models.ManyToManyField(to='books.Book'),
        ),
    ]
