# Generated by Django 2.2.3 on 2019-07-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='https://thumbs.dreamstime.com/z/ribbon-book-icon-white-background-simple-element-illustration-ui-concept-sign-symbol-design-141336047.jpg', upload_to='images/'),
        ),
    ]
