# Generated by Django 2.2.3 on 2019-07-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20190709_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.CharField(default='', max_length=300),
        ),
    ]
