# Generated by Django 2.2.3 on 2019-07-21 20:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0016_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='owner',
        ),
        migrations.AddField(
            model_name='collection',
            name='owner',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
