# Generated by Django 2.2.3 on 2019-07-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='works',
            field=models.ManyToManyField(to='books.Book'),
        ),
    ]
