# Generated by Django 2.2.3 on 2019-07-06 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_author_works'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='writer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='books.Author'),
        ),
    ]
